# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  stow:
    cmds:
      - sh ./scripts/stow.sh
  nix:
    cmds:
      - darwin-rebuild switch --flake ~/.config/nix-darwin
