[libraries]
standard = "2008"
ieee.files = [
	"ghdl/libraries/ieee/*.vhd",
]
ieee.is_third_party = true
	
[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement
