[project]
name = "catls"
version = "0.1.0"
description = "A file listing and content display tool with XML output"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyfakefs>=5.9.1",
    "pytest>=8.4.1",
]