(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'vhdl-mode)
  (package-refresh-contents)
  (package-install 'vhdl-mode))
