# This file is generated by bun2nix
# To regenerate, run: bun2nix -o bun.nix

{
  # This is a placeholder bun.nix file
  # Run 'bun install' followed by 'bun2nix -o bun.nix' to generate the actual dependencies
  dependencies = {};
  devDependencies = {};
}