name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - name: Configure Nix for cross-compilation
        run: |
          echo "extra-platforms = aarch64-darwin x86_64-linux" | sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon.service
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "conneroisu/dotfiles"
          rolling: true
          visibility: "public"
          include-output-paths: true
